### ISSUE TITLE
annotation files not found

### ISSUE THREAD

**Issue by PuneethReddyHC** [bochuanwu/Agricultural-Disease-Classification#4]
Traceback (most recent call last):
  File "gdrive/My Drive/Agricultural-Disease-Classification/invectionV3/invectionV3.py", line 110, in <module>
    trian_img_paths,train_labels = process_test(config.TRAIN_ANNOTATION_FILE,config.TRAIN_DIR)
  File "gdrive/My Drive/Agricultural-Disease-Classification/invectionV3/invectionV3.py", line 82, in process_test
    with open(anno_file) as file:
FileNotFoundError: [Errno 2] No such file or directory: './AgriculturalDisease_trainingset/AgriculturalDisease_train_annotations1.json'

**Comment by PuneethReddyHC** [comment]
Please reply

**Comment by bochuanwu** [comment]
that means you have not download the json file for label
